config/routes.rb
Rails
  .application
  .routes
  .draw do
    resources :comments, only: %i[create destroy]

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # get "blogs", to: "blogs#index"
    # get "blogs/new", to:"blogs#new"
    # post "blogs", to:"blogs#create"
    # get "blogs/:id", to:"blogs#show"
    resources :blogs
    resources :users, only: %i[new create]
    root 'home#index'
    get 'mypage', to: 'users#me'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  body       :text
#  name       :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Blog < ApplicationRecord
  # これを書くことによってblogオブジェクトからコメントが参照できるようになる
  # dependent: :delete_all -> blogを削除したときに関連するデータ(コメント、タグ)も一緒に削除される
  # delete_allのほかにdestroyもあるが、それは関連するモデルのオブジェクト一つずつに対してdestroyメソッドを呼ぶ
  # 複雑なことをしない限りdelete_allでまとめて削除した方がパフォーマンスがいい
  has_many :comments, dependent: :delete_all

  # ブログからタグを関連付ける
  has_many :blog_tag_relations, dependent: :delete_all
  has_many :tags, through: :blog_tag_relations

  validates :name, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # 実行したいメソッドをシンボルで書く
  before_action :set_target_blog, only: %i[show edit update destroy]

  def index
    # @blogs = Blog.all
    # tag_idに該当するtagを取得してtagオブジェクトから関連するブログを取得
    # tag_idがあった場合にはタグをtag_idから検索してタグに紐付くブログのリストを取得

    @blogs =
      params[:tag_id].present? ? Tag.find(params[:tag_id]).blogs : Blog.all

    # kaminariのインストールによりモデルに対してpageメソッドが使えるようになる
    @blogs = @blogs.page(params[:page])
  end

  def new
    @blog = Blog.new(flash[:blog])
  end

  def create
    blog = Blog.new(blog_params)
    if blog.save
      flash[:notice] = '投稿しました'

      # 作成した時点でIDが付与されるのでblog = blog/:idが実現する
      # viewがないのでリダイレクト
      redirect_to blog
    else
      redirect_to new_blog_path,
                  flash: {
                    # リダイレクトすると入力したフォームが消える為
                    # flashでnewアクションに渡すことで入力したままのフォームを返すことができる
                    # 渡さないと途中までの入力が消える
                    blog: blog,
                    error_messages: blog.errors.full_messages,
                  }
      # flash[:error_messages] ここにはバリデーションエラーが配列の形で格納される
    end
  end

  def show
    # @comment = @blog.comments.new
    # コメントオブジェクトでblog_idが設定されている
    @comment = Comment.new(blog_id: @blog.id)
    # @comment = @blog.comments.new(blog_id: @blog.id)
  end

  def edit
    #.attributes -> オブジェクトの属性情報（id, name, titleなど）をHashの形式で取得するメソッド
    # updateのバリデーションでelse分に入った時に@blogだとエラーが出る
    # Blogクラスのインスタンス以外のもの(フォームで入力した値)が入るためエラーになる
    @blog.attributes = flash[:blog] if flash[:blog]
  end

  def update
    # プロパティ名_値
    # memo updateはnewと違ってsaveとかないからこういう書き方 -> update ≠ save
    if @blog.update(blog_params)
      redirect_to @blog, flash: { notice: '更新できました' }
    else
      redirect_back fallback_location: @blog,
                    flash: {
                      blog: @blog,
                      error_messages: @blog.errors.full_messages,
                    }
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, flash: { notice: '削除されました' }
  end

  private

  def blog_params
    params.require(:blog).permit(:name, :title, :body, tag_ids: [])
  end

  def set_target_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= blog.title %></h4>
    <%# ここを付けなければエラーは出ないがタグも出ない %>
    <% blog.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(blog.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= blog.name %></p>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= render "shared/error_messages" %>

<%= form_with model: blog do |f| %>
  <div class="form-group">
    <%# :name -> モデルのプロパティ名 = カラム名 %>
    <%# 入力したデータをプロパティに格納 %>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <div class="form-group">
  </div>

  <div class="form-group">
    <span>タグ</span>
    <%# :tag_idsにタグのリストを渡すことでブログに複数のタグを紐付けられる %>
    <%# collection_check_boxesは存在する値の数だけチェックボックスを作成する %>
    <%# 第一引数はチェックボックスで扱うブログオブジェクトのプロパティ名 %>
    <%# 多対多の関連付けは相手のモデル名_idsとすると関連付けができる %>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%# 第四引数の:nameが表示される %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>


  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/blogs/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', blogs_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<div class="d-flex align-items-center">
  <h1>ブログ一覧</h1>
  <div class="ml-auto boards__linkBox">
  <%# ブログを送信したときにブログ一覧画面のアクションが表示される %>
  <%= form_with url: blogs_path, method: :get, class: 'boards__searchForm' do %>
  <%# セレクトボックスのnameがtag_idになる %>
  <%# options_from_collection_for_select オプション要素を複数表示 %>
      <%= select_tag :tag_id,
      # 第4引数は何を選択状態にするかの指定
      # 一度選択したタグを選択後も表示するのでparams[:tag_id]を指定
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                      #  何も選択されていない状態
                       prompt: 'タグで絞り込み',
                       class: 'form-control boards__select',
                      #  選択されるたびに実行されるJSのコード
                      # 選択肢から選んだ時点でformをサブミット
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
    <%# new_blog_path = /blogs/new %>
    <% if @current_user %>
      <%= link_to '新規作成', new_blog_path, class: "btn btn-outline-dark" %>
    <% end %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>

  <table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.name %></td>
        <td><%= blog.created_at.to_s(:datetime_jp) %></td>
        <td><%= blog.updated_at.to_s(:datetime_jp) %></td>
        <%# 第二引数に当てたオブジェクトの詳細画面へのリンクを作成 %>
        <td><%= link_to '詳細', blog, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '削除', blog, class: 'btn btn-outline-dark', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%# kaminariをインストールしたのでpaginateが使える 引数には一覧表示対象のオブジェクトのリストを渡す %>
<%= paginate @blogs%>

app/views/blogs/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', blogs_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= form_for @blog do |f| %>
 <div class="form-group">
 <%# :name -> モデルのプロパティ名 = カラム名 %>
 <%# 入力したデータをプロパティに格納 %>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>

  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/blogs/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', blogs_path, class: 'btn btn-outline-dark' %>
    <%# pathに編集対象のオブジェクトを引数として渡すことでそのオブジェクトを編集するためのURLを出力してくれる %>
    <%= link_to '編集', edit_blog_path(@blog), class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<%# object:@blogとした場合は、パーシャル名と同名のローカル変数が作成されてパーシャルに渡される %>
<%= render partial:'blog', object:@blog %>
<%# モデルのオブジェクトを表示する場合 %>
<%# render @blog %>
<div class="p-comment__list">
  <div class="p-comment__listTitle">コメント</div>
  <%# オブジェクトのリストをrenderの引数に渡した場合は
  自動的にモデル名のビューが使用され、オブジェクトの数だけ繰り返しレンダリングされる %>
  <%# renderの対象：comments %>
  <%= render @blog.comments %>
</div>

<%= render 'comments/form', comment: @comment %>