config/routes.rb
Rails
  .application
  .routes
  .draw do
    resources :comments, only: %i[create destroy]

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # get "blogs", to: "blogs#index"
    # get "blogs/new", to:"blogs#new"
    # post "blogs", to:"blogs#create"
    # get "blogs/:id", to:"blogs#show"
    resources :blogs
    resources :users, only: %i[new create]
    root 'home#index'
    get 'mypage', to: 'users#me'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  birthday        :date
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#
class User < ApplicationRecord
  # userモデルに認証機能を持たせるために記述
  has_secure_password

  validates :name,
            # 入力必須
            presence: true,
            # 同じ名前の登録NG
            uniqueness: true,
            length: {
              maximum: 16,
            },
            format: {
              with: /\A[a-z0-9]+\z/,
              # エラー時にデフォルトエラーが「不正な入力」の為明示的にエラー分を設定
              message: 'は小文字英数字で入力してください',
            }

  # 最低文字数のバリデーションを設定するとpresenceを設定しなくても
  # 空の入力でエラーがでるようになる
  validates :password, length: { minimum: 8 }

  def age
    # 日本の現在時間
    now = Time.zone.now
    # 10_000で割って年数を取得
    (now.strftime('%Y%m%d').to_i - birthday.strftime('%Y%m%d').to_i) / 10_000
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # createのバリデーションエラーでホームに戻された場合も
    # 引数にしてしておくことで入力したユーザー名が消えずに残る
    @user = User.new(flash[:user])
  end

  # formをsubmitしたらcreateメソッドが呼ばれる
  def create
    # フォームから送信されてたuserのパラメーターから新しいuserオブジェクトを作成
    user = User.new(user_params)

    # パスワードとパスワード再入力が一致しているかもバリデーションしてくれる
    if user.save
      # session変数はsession情報を扱う為の特殊な変数で
      # session変数の任意のキーに値をセットすることで
      # ページを跨いで変数の値を保持することができる
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      # ホーム画面に戻す
      flash[:user] = user
      flash[:error_messages] = user.errors.full_messages
      redirect_back fallback_location: 'http://localhost'
      # redirect_to :back,
      #             flash: {
      #               user: user,
      #               error_messages: user.errors.full_messages,
      #             }
    end
  end

  def me; end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class='alert alert-danger'>
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
  <%# userモデルに属性は存在するがテーブルにカラムは存在しない %>
  <%# パスワードはpassword_digestというカラムに保存される %>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/users/_login_form.html.erb
<h1>ログイン</h1>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<%# モデルを使わずにinput要素のnameをネストしたい場合scopeに渡す %>
<%# ex) session[name]とか %>
<%# nameにsessionと入ることでparams[:session]で取得できるようになる %>
<%= form_with scope: :session, url: login_path do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'ログイン', class: 'btn btn-primary' %>
<% end %>

app/views/users/me.html.erb
<h1>マイページ</h1>
name: <%= @current_user.name %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= render partial:"form", locals: { user: @user }%>