config/routes.rb
Rails
  .application
  .routes
  .draw do
    resources :comments, only: %i[create destroy]

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # get "blogs", to: "blogs#index"
    # get "blogs/new", to:"blogs#new"
    # post "blogs", to:"blogs#create"
    # get "blogs/:id", to:"blogs#show"
    resources :blogs
    resources :users, only: %i[new create]
    root 'home#index'
    get 'mypage', to: 'users#me'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ApplicationControllerは全てのコントローラーで継承している
  # CSRF(クロスサイトリクエストフォージェリ)対策：Webアプリケーションの脆弱性を利用したサイバー攻撃の一種
  protect_from_forgery with: :exception

  # 全てのアクションの前に呼び出される
  before_action :current_user

  private

  def current_user
    # sessionにuser_idがなければreturn
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # アプリ全体で使用するヘルパーメソッドを記述
  # 特定のコントローラーのviewで使用されるヘルパーなら名前を合わせたフォルダに記述した方が分かりやすい

  def header_link_item(name, path)
    # bootstrapに合わせる為記述
    class_name = 'nav-item'

    # current_page?(path) -> 表示するpathと引数のpathが同一か判断
    # 同じならクラスの指定にactiveを追加
    class_name << ' active' if current_page?(path)

    # 任意のhtmlタグを作る
    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" id="blog-list">
        <%# link_toではなく独自のヘルパーを使用 %>
        <%# 何故なら表示中のページのみアクティブな状態の見た目にする為 %>
        <%= header_link_item('一覧', blogs_path) %>
      </li>
      <%# <li class="nav-item" id="blog-list">
        <%= header_link_item('一覧', blogs_path) %>
      <%# </li>  %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%# ログインしているかどうかでメニューが切り替わる %>
          <% if @current_user %>
            <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %> 
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
            <%= link_to 'ログイン', root_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>